

# 별도로 settings.gradle 파일을 복사
COPY settings.gradle .

RUN ./gradlew2 bootJar

# 실행 단계
FROM openjdk:11-jre-slim

WORKDIR /admin

# 빌드된 JAR 파일을 복사합니다.
COPY --from=build /som/admin/build/libs/*.jar admin.jar

# settings.gradle 파일을 복사합니다.
COPY settings.gradle .

# 컨테이너가 시작될 때 애플리케이션을 실행합니다.
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar", "admin.jar"]